### PR TITLE
docker support

### PR DESCRIPTION
**Pull request by ghost**
A better way would be to do this with env variables.

### CODE REVIEW

**Comment by dkay0670** [comment]
docker sucks balls

**Comment by ghost** [comment]
why are you still trying

**Comment by HIDEN64** [comment]
no

**Comment by ghost** [comment]
> why are you still trying

I know. I'm sorry. I recognized my words and actions were wrong, so I grew up and learned from them. Not a little kid anymore. If you don't care, close my pr. I contributed something I thought would be useful.

> docker sucks balls

Don't trust that darned Microsoft spyware.

**Comment by dkay0670** [comment]
what does Microsoft have anything to do with docker sucking

**Comment by ghost** [comment]
> what does Microsoft have anything to do with docker sucking

I mean .NET

**Comment by ghost** [comment]
https://git.revvy.de/Revvy/Discord-IRC-Sharp
hxxp://git[.]revvybrr6pvbx4n3j4475h4ghw4elqr4t5xo2vtd3gfpu2nrsnhh57id[.]onion/Revvy/Discord-IRC-Sharp
hxxp://revuxn3ppgnjsfewec7zsnpdf63ygqdchndiebiew3rcolf3dy3q[.]b32[.]i2p/Revvy/Discord-IRC-Sharp

**Pull request closed without merging**
